### Create sensor
POST http://localhost:8080/api/sensors
Content-Type: application/json

{
	"name": "Sensor {{$random.integer}}",
	"ip": "{{$random.internet.ipV4Address}}",
	"location": "{{$random.address.cityName}}",
	"protocol": "HTTP",
	"model": "S{{$random.integer}}-HTTP"
}
> {% client.global.set("sensor_id", response.body.id); %}

### Find sensor by TSID
GET http://localhost:8080/api/sensors/{{sensor_id}}

### Find sensor by TSID with detail
GET http://localhost:8080/api/sensors/{{sensor_id}}/detail

### Find all
GET http://localhost:8080/api/sensors?page=0&size=5&sort=id,desc

### Update sensor by TSID
PUT http://localhost:8080/api/sensors/{{sensor_id}}
Content-Type: application/json

{
	"name": "Sensor UPDATED {{$random.integer}}",
	"ip": "{{$random.internet.ipV4Address}}",
	"location": "{{$random.address.cityName}}",
	"protocol": "HTTP",
	"model": "S{{$random.integer}}-HTTP"
}

### Delete sensor by TSID
DELETE http://localhost:8080/api/sensors/{{sensor_id}}

### ENABLE sensor by TSID
PUT http://localhost:8080/api/sensors/{{sensor_id}}/enable

### DISABLE sensor by TSID
DELETE http://localhost:8080/api/sensors/{{sensor_id}}/enable