### Create sensor
POST http://localhost:8080/api/sensors
Content-Type: application/json

{
	"name": "Sensor {{$random.integer}}",
	"ip": "{{$random.internet.ipV4Address}}",
	"location": "{{$random.address.cityName}}",
	"protocol": "HTTP",
	"model": "S{{$random.integer}}-HTTP"
}

### Find sensor by TSID
GET http://localhost:8080/api/sensors/0NT9AV69REJ1P

### Find all
GET http://localhost:8080/api/sensors?page=0&size=5&sort=id,desc